services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vrtx
    ports:
      - "5400:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - app_network
    ports:
      - "5001:5001"

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
